services:
    Gally\Stitching\Decoration\GraphQl\Type\StitchingFieldsBuilder:
        decorates: api_platform.graphql.fields_builder
        arguments:
            - '@Gally\Metadata\Repository\MetadataRepository'
            - '@ApiPlatform\Core\Metadata\Resource\Factory\ResourceMetadataFactoryInterface'
            - '@Gally\ResourceMetadata\Service\ResourceMetadataManager'
            - '@api_platform.graphql.types_container'
            - '@.inner'

    Gally\Stitching\Serializer\GraphQl\StitchingNormalizer:
        arguments:
            - '@Gally\Metadata\Repository\MetadataRepository'
            - '@ApiPlatform\Core\Metadata\Resource\Factory\ResourceMetadataFactoryInterface'
            - '@Gally\ResourceMetadata\Service\ResourceMetadataManager'
            - '@Gally\Stitching\Service\SerializerService'
        tags:
            - { name: 'serializer.normalizer' }

    Gally\Stitching\Service\SerializerService:
        arguments:
            - '@Gally\Metadata\Repository\MetadataRepository'
            - '@Gally\Metadata\Repository\SourceFieldRepository'
