elasticsuite:
    entities:
        product:
            static_fields:
                - name: 'id'
                  type: 'integer'
                - name: 'sku'
                  type: 'keyword'
                - name: 'price'
                  type: 'price'
                - name: 'stock.status'
                  type: 'boolean'
                - name: 'stock.quantity'
                  type: 'double'
