services:    
    Elasticsuite\Catalog\Repository\Catalog\CatalogRepository:
        arguments:
            - '@Doctrine\Persistence\ManagerRegistry'
        tags:
            - { name: doctrine.repository_service } 

    Elasticsuite\Catalog\Repository\Website\WebsiteRepository:
        arguments:
            - '@Doctrine\Persistence\ManagerRegistry'
        tags:
            - { name: doctrine.repository_service }

    Elasticsuite\Catalog\Repository\Catalog\CatalogRepositoryInterface: '@Elasticsuite\Catalog\Repository\Catalog\CatalogRepository'
    Elasticsuite\Catalog\Repository\Website\WebsiteRepositoryInterface: '@Elasticsuite\Catalog\Repository\Website\WebsiteRepository'
