services:
    Gally\Index\Converter\SourceField\BasicSourceFieldConverter:
        tags:
            - { name: gally.mapping.source_field_converter }
            
    Gally\Index\Converter\SourceField\ImageSourceFieldConverter:
        tags:
            - { name: gally.mapping.source_field_converter }
        
    Gally\Index\Converter\SourceField\ObjectSourceFieldConverter:
        tags:
            - { name: gally.mapping.source_field_converter }
        
    Gally\Index\Converter\SourceField\PriceSourceFieldConverter:
        tags:
            - { name: gally.mapping.source_field_converter }
        
    Gally\Index\Converter\SourceField\ReferenceSourceFieldConverter:
        tags:
            - { name: gally.mapping.source_field_converter }
        
    Gally\Index\Converter\SourceField\SelectSourceFieldConverter:
        tags:
            - { name: gally.mapping.source_field_converter }

    Gally\Index\Converter\SourceField\StockSourceFieldConverter:
        tags:
            - { name: gally.mapping.source_field_converter }

    Gally\Index\Converter\SourceField\CategorySourceFieldConverter:
        tags:
            - { name: gally.mapping.source_field_converter }

    Gally\Index\Converter\SourceField\TextSourceFieldConverter:
        tags:
            - { name: gally.mapping.source_field_converter }
        
