elasticsuite:
    menu:
#       Todo: Move menu item configuration (with translations) in modules when they wil lbe created
        dashboard:
            order: 10

        analyze:
            order: 20
        analyze_catalog_structure:
            order: 10
            parent: analyze
        analyze_search_usage:
            order: 20
            parent: analyze
        analyze_ab_testing:
            order: 30
            parent: analyze

        merchandize:
            order: 30
        merchandize_categories:
            order: 10
            parent: merchandize
        merchandize_search_results:
            order: 20
            parent: merchandize
        merchandize_recommender:
            order: 30
            parent: merchandize
        merchandize_recommender_configuration:
            order: 10
            parent: merchandize_recommender
        merchandize_recommender_manual_recommenders:
            order: 20
            parent: merchandize_recommender
        merchandize_recommender_auto_recommenders:
            order: 30
            parent: merchandize_recommender
        merchandize_recommender_behavioral_recommenders:
            order: 30
            parent: merchandize_recommender
        merchandize_recommender_boosts:
            order: 40
            parent: merchandize
  
        search:
            order: 40
        search_configuration:
            order: 10
            parent: search
        search_configuration_relevance:
            order: 10
            parent: search_configuration
        search_configuration_autocompletion:
            order: 20
            parent: search_configuration
        search_configuration_attributes:
            order: 30
            parent: search_configuration
        search_facets:
            order: 20
            parent: search
        search_thesasurus:
            order: 30
            parent: search

        monitoring:
            order: 50
        monitoring_index:
            order: 10
            parent: monitoring
        monitoring_imports:
            order: 20
            parent: monitoring

        settings:
            order: 100
        settings_global_configuration:
            order: 10
            parent: settings
        settings_data_collection:
            order: 20
            parent: settings
        settings_data_collection_behavioral_data_configuration:
            order: 10
            parent: settings_data_collection
        settings_data_collection_tracking:
            order: 20
            parent: settings_data_collection
        settings_data_collection_telemetry_beacon:
            order: 30
            parent: settings_data_collection
        settings_interfaces:
            order: 100
            parent: settings
