services:
    Elasticsuite\VirtualCategory\Decoration\Product\GraphQl\Type\Definition\Filter\CategoryTypeDefaultFilterInputType:
        decorates: Elasticsuite\Entity\GraphQl\Type\Definition\Filter\CategoryTypeDefaultFilterInputType
        arguments:
            - '@Elasticsuite\RuleEngine\Service\RuleEngineManager'
            - '@Elasticsuite\Category\Repository\CategoryRepository'
            - '@Elasticsuite\Category\Repository\CategoryConfigurationRepository'
            - '@Elasticsuite\Search\Elasticsearch\Builder\Request\Query\Filter\FilterQueryBuilder'
            - '@Elasticsuite\Search\Elasticsearch\Request\QueryFactory'
            - '@logger' 
            - '%api_platform.graphql.nesting_separator%'
        decoration_priority: 10

    Elasticsuite\VirtualCategory\Decoration\Repository\CategoryProductPositionIndexer\CategoryProductPositionIndexerRepository:
        decorates: Elasticsuite\Category\Repository\CategoryProductPositionIndexer\CategoryProductPositionIndexerRepository
        arguments:
            - '@api_platform.elasticsearch.client'
            - '@Elasticsuite\Metadata\Repository\MetadataRepository'
            - '@Elasticsuite\Index\Service\IndexSettings'
            - '@Elasticsuite\Index\Repository\Index\IndexRepositoryInterface'
            - '@logger'
            - '@Elasticsuite\Category\Repository\CategoryConfigurationRepository'
            - '@Elasticsuite\Category\Repository\CategoryRepository'
        decoration_priority: 10
