services:
    Gally\Bundle\DataProvider\ExtraBundleDataProvider:
        arguments:
            - '@Symfony\Component\HttpKernel\KernelInterface'
        tags:
            - { name: api_platform.collection_data_provider }
