x-base-php-env : &php-base-env
  APP_ENV: ${APP_SECRET}
  XDEBUG_MODE: off

services:

  router:
    build:
      context: ./docker/router
    environment:
      - EXAMPLE_UPSTREAM=pwa:3000

  php:
    environment:
      <<: *php-base-env

  cron:
    environment:
      <<: *php-base-env

  pwa:
    build:
      target: gally_pwa_int
      args:
        - public_url=https://${SERVER_NAME}/example
