# Development environment override
services:
  
  certbot:
    environment:
      - SELF_SIGNED=true
  
  router:
    volumes:
      - ./api/public:/app/public
    depends_on:
      - example
    environment:
      - EXAMPLE_UPSTREAM=example:3001

  php:
    build:
      target: gally_php_dev
    volumes: !override
      - ./api:/app:rw,cached,z
      - ./docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro,z
    environment:
      - APP_ENV=${APP_ENV:-dev}
      # See https://xdebug.org/docs/all_settings#mode
      - XDEBUG_MODE=${XDEBUG_MODE:-off}
      - PHP_IDE_CONFIG=serverName=gally
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
    tty: true

  pwa:
    user: ${UUID?You must set UUID env var}:${GUID?You must set GUID env var}
    build:
      target: gally_pwa_dev
      args:
        - NEXT_PUBLIC_ENTRYPOINT=${SERVER_NAME:-gally.localhost}
        - NEXT_PUBLIC_API_URL=https://${SERVER_NAME:-gally.localhost}/${API_ROUTE_PREFIX:-api}
    volumes:
      - ./front:/usr/src/front:rw,cached,z
    environment:
      # On Linux, you may want to comment the following line for improved performance
      - WATCHPACK_POLLING="true"

  example:
    user: ${UUID?You must set UUID env var}:${GUID?You must set GUID env var}
    build:
      context: ./docker/front
      target: gally_example_dev
      additional_contexts: 
        front_src: ./front
      args:
        - REACT_APP_API_URL=https://${SERVER_NAME:-gally.localhost}/${API_ROUTE_PREFIX:-api}
    volumes:
      - ./front:/usr/src/front:rw,cached,z
    environment:
      - PUBLIC_URL=https://${SERVER_NAME:-gally.localhost}/example
      - REACT_APP_API_URL=https://${SERVER_NAME:-gally.localhost}/${API_ROUTE_PREFIX:-api}

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
###< doctrine/doctrine-bundle ###

  redis:
    ports:
      - '6379:6379'
