# Development environment override
x-base-php-env : &php-base-env
  APP_ENV: ${APP_ENV:-dev}
  MAILER_DSN: ${MAILER_DSN:-smtp://mailer:1025}

x-base-php: &php-base
  build:
    target: gally_php_dev
  volumes: !override
    - ./api:/app:rw,cached,z
    - ./docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro,z
    - job_files:/app/var/job:rw
  environment: *php-base-env
  extra_hosts:
    # Ensure that host.docker.internal is correctly defined on Linux
    - host.docker.internal:host-gateway
  tty: true


services:
  proxy:
    ports: !override
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    environment:
      - HTTPS_PORT=${HTTPS_PORT:-443}

  certbot:
    environment:
      - SELF_SIGNED=true

  varnish:
    environment:
      - CRON_UPSTREAM=${CRON_UPSTREAM:-}

  router:
    volumes:
      - ./api/public:/app/public
    depends_on:
      - example
    environment:
      - EXAMPLE_UPSTREAM=example:3001

  php:
    <<: *php-base
    environment:
      <<: *php-base-env
      TRUSTED_HOSTS: ${TRUSTED_HOSTS:-^${SERVER_NAME:-|gally.localhost}|localhost|${E2E_SERVER_NAME:-gally.e2e}|php$$}
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: ${XDEBUG_MODE:-off}
      PHP_IDE_CONFIG: serverName=gally

  cron:
    <<: *php-base
    profiles:
      - cron

  pwa:
    user: ${UUID?You must set UUID env var}:${GUID?You must set GUID env var}
    build:
      target: gally_pwa_dev
      args:
        - NEXT_PUBLIC_ENTRYPOINT=
        - NEXT_PUBLIC_API_URL=
        - REACT_APP_API_URL=
    volumes:
      - ./front:/usr/src/front:rw,cached,z
    environment:
      - SKIP_YARN_INSTALL=${SKIP_YARN_INSTALL:-false}
      # On Linux, you may want to comment the following line for improved performance
      - WATCHPACK_POLLING="true"
      - NEXT_PUBLIC_ENTRYPOINT=
      - NEXT_PUBLIC_API_URL=
      - REACT_APP_API_URL=

  example:
    user: ${UUID?You must set UUID env var}:${GUID?You must set GUID env var}
    build:
      context: ./docker/front
      target: gally_example_dev
      additional_contexts:
        front_src: ./front
    volumes:
      - ./front:/usr/src/front:rw,cached,z
    environment:
      - PUBLIC_URL=https://${SERVER_NAME:-gally.localhost}/example
      - SKIP_YARN_INSTALL=${SKIP_YARN_INSTALL:-false}

  e2e:
    extends:
      file: ./compose.e2e.yml
      service: e2e
    volumes:
      - ./front/e2e/:/usr/src/app:rw,cached,z

  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    labels:
      - traefik.enable=true
      - traefik.http.services.gally-mail-$COMPOSE_PROJECT_NAME-http.loadbalancer.server.port=8025
      # Serve gally over http
      - traefik.http.routers.gally-mail-$COMPOSE_PROJECT_NAME-http.rule=Host(`mail.${SERVER_NAME:-gally.localhost}`)
      - traefik.http.routers.gally-mail-$COMPOSE_PROJECT_NAME-http.entrypoints=http
      # Serve gally over https
      - traefik.http.routers.gally-mail-$COMPOSE_PROJECT_NAME-https.rule=Host(`mail.${SERVER_NAME:-gally.localhost}`)
      - traefik.http.routers.gally-mail-$COMPOSE_PROJECT_NAME-https.entrypoints=https
      - traefik.http.routers.gally-mail-$COMPOSE_PROJECT_NAME-https.tls=true

