x-base-php-env : &php-base-env
  APP_ENV: dev
  XDEBUG_MODE: off
  MAILER_DSN: ${MAILER_DSN:-smtp://mailer:1025}

x-base-php: &php-base
  build:
    target: gally_php_dev
  volumes: !override
    - ./api:/app:rw,cached,z
    - ./docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro,z
  environment: *php-base-env
  
services:
  
  certbot:
    environment:
      - SELF_SIGNED=true
  
  php:
    <<: *php-base
    environment:
      <<: *php-base-env
      TRUSTED_HOSTS: ${TRUSTED_HOSTS:-^${SERVER_NAME:-|gally.localhost}|localhost|${E2E_SERVER_NAME:-gally.e2e}|php$$}

  cron:
    <<: *php-base
    environment:
      <<: *php-base-env
      CRONTAB: ~

  pwa:
    build:
      target: gally_pwa_ci
    volumes:
      - ./front/example-app/coverage:/usr/src/front/example-app/coverage:rw,cached,z
      - ./front/pwa/coverage:/usr/src/front/pwa/coverage:rw,cached,z
    environment:
      - NEXT_PUBLIC_ENTRYPOINT=
      - NEXT_PUBLIC_API_URL=
      - REACT_APP_API_URL=
  example:
    build:
      context: ./docker/front
      target: gally_example_ci
      additional_contexts:
        front_src: ./front

  e2e:
    extends:
      file: ./compose.e2e.yml
      service: e2e
    environment:
      - CI=true
