services:
  
  certbot:
    environment:
      - SELF_SIGNED=true

  router:
    build:
      context: ./docker/router
    environment:
      - EXAMPLE_UPSTREAM=pwa:3000

  php:
    environment:
      - APP_SECRET=${APP_SECRET}
      - XDEBUG_MODE='off'

  pwa:
    build:
      target: gally_pwa_int
      args:
        - public_url=https://${SERVER_NAME}/example
