services:
  proxy_init_certs:
    build:
      context: ./docker/proxy-init-certs
    ports:
      - "80:80"
    volumes:
      - ./docker/certbot/certs:/etc/nginx/certs
      - certbot_www:/var/www/certbot
    environment:
      - SERVER_NAME=${SERVER_NAME:-gally.localhost}
        
  certbot_init_certs:
    build:
      context: ./docker/certbot-init-certs
    volumes:
      - ./docker/certbot/certs:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    environment:
      - SERVER_NAME=${SERVER_NAME:-gally.localhost}

volumes:
  certbot_www:
