
version: "3.4"

# Production environment override
services:
  php:
    environment:
      APP_ENV: dev # Needed for fixtures bundles to work.
      APP_SECRET: ${APP_SECRET}
      # MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET}
      XDEBUG_MODE: 'off'

  caddy:
    environment:
      EXAMPLE_UPSTREAM: pwa:3000
      # MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      # MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}

  database:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  pwa:
    build:
      context: ./front
      target: gally_pwa_int
      args:
        public_url: https://${SERVER_NAME}/example
