
version: "3.4"

# Production environment override
services:
  php:
    environment:
      APP_ENV: dev # Needed for fixtures bundles to work.

  caddy:
    environment:
      EXAMPLE_UPSTREAM: pwa:3000

  pwa:
    build:
      context: ./front
      target: gally_pwa_int
      args:
        public_url: https://${SERVER_NAME}/example
