version: "3.4"

# Development environment override
services:
  php:
    build:
      target: api_platform_php_dev
    volumes:
      - ./api:/srv/api:rw,cached,z
      - ./api/docker/php/conf.d/api-platform.dev.ini:/usr/local/etc/php/conf.d/api-platform.ini:z
      # if you develop on Linux, you may use a bind-mounted host directory instead
      - ./api/var:/srv/api/var:rw,z
    # If supported by your version of docker/docker-compose
    # extra_hosts:
    #  - host.docker.internal:host-gateway
    environment:
      APP_ENV: dev
      # Lots of change between Xdebug 2 and Xdebug 3, see https://xdebug.org/docs/upgrade_guide
      # and https://xdebug.org/docs/all_settings
      # XDEBUG_MODE: debug
      XDEBUG_CONFIG: >-
        # Replaces remote_connect_back=1
        discover_client_host=1
        # Replaces remote_autostart=1
        start_with_request=1
        # Will only work if host-gateway is supported
        # client_host=host.docker.internal
        # Default IP of docker0 interface (bridge)
        # client_host=172.17.0.1
        client_port=9000
        idekey=PHPSTORM
      PHP_IDE_CONFIG: serverName=api-platform

  pwa:
    build:
      context: ./front
      target: api_platform_pwa_ci
    volumes:
      - ./front/example-app/coverage:/usr/src/front/example-app/coverage:rw,cached,z
      - ./front/pwa/coverage:/usr/src/front/pwa/coverage:rw,cached,z

  example:
    build:
      context: ./front
      target: api_platform_example_ci

  caddy:
    volumes:
      - ./api/docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro,z
      - ./api/public:/srv/api/public:ro,z
    depends_on:
      - php
      - pwa
      - example
    environment:
      EXAMPLE_UPSTREAM: example:3001
      # MERCURE_EXTRA_DIRECTIVES: demo

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
###< doctrine/doctrine-bundle ###

###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###
