version: "3.4"

# Development environment override
services:
  php:
    build:
      target: api_platform_php_dev
    volumes:
      - ./api:/srv/api:rw,cached
      - ./api/docker/php/conf.d/api-platform.dev.ini:/usr/local/etc/php/conf.d/api-platform.ini
      # if you develop on Linux, you may use a bind-mounted host directory instead
      - ./api/var:/srv/api/var:rw
    # If supported by your version of docker/docker-compose
    # extra_hosts:
    #  - host.docker.internal:host-gateway
    environment:
      APP_ENV: dev
      # Lots of change between Xdebug 2 and Xdebug 3, see https://xdebug.org/docs/upgrade_guide
      # and https://xdebug.org/docs/all_settings
      # XDEBUG_MODE: debug
      XDEBUG_CONFIG: >-
        # Replaces remote_connect_back=1
        discover_client_host=1
        # Replaces remote_autostart=1
        start_with_request=1
        # Will only work if host-gateway is supported
        # client_host=host.docker.internal
        # Default IP of docker0 interface (bridge)
        # client_host=172.17.0.1
        client_port=9000
        idekey=PHPSTORM
      PHP_IDE_CONFIG: serverName=api-platform

  pwa:
    user: ${UUID?You must set UUID env var}:${GUID?You must set GUID env var}
    build:
      context: ./front
      target: api_platform_pwa_dev
    volumes:
      - ./front:/usr/src/front:rw,cached

  example:
    user: ${UUID?You must set UUID env var}:${GUID?You must set GUID env var}
    build:
      context: ./front
      target: api_platform_example_dev
    volumes:
      - ./front:/usr/src/front:rw,cached
    environment:
      PUBLIC_URL: https://localhost/example

  caddy:
    volumes:
      - ./api/docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./api/public:/srv/api/public:ro
    depends_on:
      - php
      - pwa
      - example
    environment:
      EXAMPLE_UPSTREAM: example:3001
      # MERCURE_EXTRA_DIRECTIVES: demo

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
###< doctrine/doctrine-bundle ###

###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###
