# Read the documentation: https://github.com/coopTilleuls/CoopTilleulsForgotPasswordBundle/blob/master/Resources/doc/getting_started.md
coop_tilleuls_forgot_password:
    password_token:
        class: Gally\User\Entity\PasswordToken
        expires_in: 1 day
        user_field: user
        serialization_groups: []
    user:
        class: Gally\User\Entity\User
        email_field: email
        password_field: password
