nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: 
            - 'Content-Type'
            - 'Authorization'
            - 'Preload'
            - 'Fields'
            # TODO Move this into Gally Bundle ?
            - !php/const Gally\Locale\EventSubscriber\LocaleSubscriber::GALLY_LANGUAGE_HEADER
            - !php/const Gally\Entity\Service\PriceGroupProvider::PRICE_GROUP_ID
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': null
