services:  
    # Declare command gally:example:cache-get
    Gally\Example\Command\Cache\GetCommand:
        arguments:
            - '@Symfony\Contracts\Translation\TranslatorInterface'
            - '@Psr\Cache\CacheItemPoolInterface'
            - null
        tags:
            - { name: console.command }
        
    # Declare gally.example* cache pools
    gally.example:
        parent: cache.app.taggable
        # Will not be directly usable nor listed through cache:pool:list
        abstract: true
        tags:
            # Allowed: "clearer", "provider", "name", "namespace", "default_lifetime", "early_expiration_message_bus" and "reset"
            - { name: cache.pool }
            
    gally.example.custom.cache:
        parent: gally.example
        tags:
            # If neither 'namespace' is defined here nor a 'class' defined above, the namespace will be the environment seed prefix
            - { name: cache.pool, namespace: 'custom' }
            
    gally.example.other.cache:
        parent: gally.example
        tags:
            - { name: cache.pool, namespace: 'other' }
    
    # Declare command gally:example:cache-get-custom
    Gally\Example\Command\Cache\GetCustomCommand:
        arguments:
            - '@gally.example.custom.cache'
            - '@Symfony\Contracts\Translation\TranslatorInterface'
            - null
        tags:
            - { name: console.command }
    
    # Declare command gally:example:cache-get-other
    Gally\Example\Command\Cache\GetOtherCommand:
        arguments:
            - '@gally.example.other.cache'
            - '@Symfony\Contracts\Translation\TranslatorInterface'
            - null
        tags:
            - { name: console.command }

    # Declare command gally:example:cache-delete
    Gally\Example\Command\Cache\DeleteCommand:
        arguments:
            - '@Psr\Cache\CacheItemPoolInterface'
            - null
        tags:
            - { name: console.command }

    # Declare command gally:example:cache-invalidate-tags
    Gally\Example\Command\Cache\InvalidateTagsCommand:
        arguments:
            - ['gally.example.custom.cache', 'gally.example.other.cache']
            - null
        tags:
            - { name: console.command }

    # Declare command gally:example:cache-invalidate-tags-injected
    Gally\Example\Command\Cache\InvalidateTagsInjectedCommand:
        arguments:
            - ['@gally.example.custom.cache', '@gally.example.other.cache']
            - null
        tags:
            - { name: console.command }
