services:
    elasticsuite.container_configuration.product_catalog.factory:
        parent: 'Elasticsuite\Search\Elasticsearch\Request\Container\Configuration\GenericContainerConfigurationFactory'
        tags:
            - { name: elasticsuite.container_configuration.factory, requestType: product_catalog, metadata: product }

    elasticsuite.container_configuration.product_search.factory:
        parent: 'Elasticsuite\Search\Elasticsearch\Request\Container\Configuration\GenericContainerConfigurationFactory'
        tags:
            - { name: elasticsuite.container_configuration.factory, requestType: product_search, metadata: product }
