services:
    Elasticsuite\Configuration\DataProvider\ConfigurationDataProvider:
        arguments:
            - '%elasticsuite.base_url%'
        tags:
            - { name: api_platform.collection_data_provider }
