services:
    Elasticsuite\Index\Decoration\Metadata\Document\Factory\AttributeDocumentMetadataFactory:
        decorates: api_platform.elasticsearch.metadata.document.metadata_factory
        arguments:
            - '@Elasticsuite\Fixture\Service\ElasticsearchFixtures'
            - '@api_platform.metadata.resource.metadata_factory'
            - '@.inner'
        decoration_priority: 100

    Elasticsuite\Index\Repository\Document\DocumentRepositoryInterface: '@Elasticsuite\Index\Repository\Document\DocumentRepository'
    Elasticsuite\Index\Repository\Document\DocumentRepository:
        arguments:
            - '@api_platform.elasticsearch.client'

    Elasticsuite\Index\Repository\Index\IndexRepositoryInterface: '@Elasticsuite\Index\Repository\Index\IndexRepository'
    Elasticsuite\Index\Repository\Index\IndexRepository:
        arguments:
            - '@api_platform.elasticsearch.client'

    Elasticsuite\Index\Repository\Metadata\MetadataRepository:
        arguments:
            - '@Doctrine\Persistence\ManagerRegistry'
        tags:
            - { name: doctrine.repository_service }

    Elasticsuite\Index\Repository\Metadata\SourceFieldRepository:
        arguments:
            - '@Doctrine\Persistence\ManagerRegistry'
        tags:
            - { name: doctrine.repository_service }

    Elasticsuite\Index\Repository\Metadata\SourceFieldLabelRepository:
        arguments:
            - '@Doctrine\Persistence\ManagerRegistry'
        tags:
            - { name: doctrine.repository_service }

    Elasticsuite\Index\Repository\Metadata\SourceFieldOptionRepository:
        arguments:
            - '@Doctrine\Persistence\ManagerRegistry'
        tags:
            - { name: doctrine.repository_service }

    Elasticsuite\Index\Repository\Metadata\SourceFieldOptionLabelRepository:
        arguments:
            - '@Doctrine\Persistence\ManagerRegistry'
        tags:
            - { name: doctrine.repository_service }

    Elasticsuite\Index\DataPersister\DocumentDataPersister:
        arguments:
            - '@Elasticsuite\Index\Repository\Document\DocumentRepositoryInterface'
        tags:
            - { name: api_platform.data_persister }

    Elasticsuite\Index\DataPersister\IndexDataPersister:
        arguments:
            - '@Elasticsuite\Index\Repository\Index\IndexRepositoryInterface'
        tags:
            - { name: api_platform.data_persister }

    Elasticsuite\Index\DataProvider\IndexDataProvider:
        arguments:
            - '@Elasticsuite\Index\Repository\Index\IndexRepositoryInterface'
        tags:
            - { name: api_platform.item_data_provider }
            - { name: api_platform.collection_data_provider }

    Elasticsuite\Index\Converter\SourceFieldToMappingField: ~
    
    Elasticsuite\Index\Service\IndexManager:
        arguments:
            - '@Elasticsuite\Index\Converter\SourceFieldToMappingField'
            - '%elasticsuite.entities%'

    Elasticsuite\Index\Helper\IndexSettings:
        arguments:
            - '@Elasticsuite\Catalog\Repository\LocalizedCatalogRepository'
            - '%elasticsuite.indices_settings%'

    Elasticsuite\Index\Api\IndexSettingsInterface: '@Elasticsuite\Index\Service\IndexSettings'
    Elasticsuite\Index\Service\IndexSettings:
        arguments:
            - '@Elasticsuite\Index\Helper\IndexSettings'

    Elasticsuite\Index\MutationResolver\CreateIndexMutation:
        arguments:
            - '@Elasticsuite\Index\Repository\Index\IndexRepositoryInterface'
            - '@Elasticsuite\Catalog\Repository\LocalizedCatalogRepository'
            - '@Elasticsuite\Index\Repository\Metadata\MetadataRepository'
            - '@Elasticsuite\Index\Service\IndexSettings'
            - '@Elasticsuite\Index\Service\IndexManager'
        tags:
            - {name: api_platform.graphql.mutation_resolver }
    
    Elasticsuite\Index\MutationResolver\BulkIndexMutation:
        arguments:
            - '@Elasticsuite\Index\Repository\Index\IndexRepositoryInterface'
        tags:
            - {name: api_platform.graphql.mutation_resolver }
    
    Elasticsuite\Index\MutationResolver\BulkDeleteIndexMutation:
        arguments:
            - '@Elasticsuite\Index\Repository\Index\IndexRepositoryInterface'
        tags:
            - {name: api_platform.graphql.mutation_resolver }

    Elasticsuite\Index\Command\IndexClearCommand:
        arguments:
            - '@Elasticsuite\Index\Repository\Index\IndexRepositoryInterface'
            - null
        tags:
            - { name: console.command }

    Elasticsuite\Index\Command\MappingGenerateCommand:
        arguments:
            - '@Elasticsuite\Index\Repository\Metadata\MetadataRepository'
            - '@Elasticsuite\Index\Service\IndexManager'
            - 'elasticsuite:mapping:get'
        tags:
            - { name: console.command }

    Elasticsuite\Index\Command\MappingStatusCommand:
        arguments:
            - '@Elasticsuite\Index\Repository\Metadata\MetadataRepository'
            - '@Elasticsuite\Index\Service\IndexManager'
            - 'elasticsuite:mapping:status'
        tags:
            - { name: console.command }           
    
    Elasticsuite\Index\DataProvider\MappingStatusDataProvider:
        arguments:
            - '@Elasticsuite\Index\Repository\Metadata\MetadataRepository'
            - '@Elasticsuite\Index\Service\IndexManager'
        tags:
            - { name: api_platform.item_data_provider }
            - { name: api_platform.graphql.query_resolver }
