services:
    Elasticsuite\Index\Decoration\Metadata\Document\Factory\AttributeDocumentMetadataFactory:
        decorates: api_platform.elasticsearch.metadata.document.metadata_factory
        arguments:
            - '@Elasticsuite\Fixture\Service\ElasticsearchFixtures'
            - '@api_platform.metadata.resource.metadata_factory'
            - '@Elasticsuite\ResourceMetadata\Service\ResourceMetadataManager'
            - '@.inner'
        decoration_priority: 100

    Elasticsuite\Index\Repository\Document\DocumentRepositoryInterface: '@Elasticsuite\Index\Repository\Document\DocumentRepository'
    Elasticsuite\Index\Repository\Document\DocumentRepository:
        arguments:
            - '@api_platform.elasticsearch.client'

    Elasticsuite\Index\Repository\Index\IndexRepositoryInterface: '@Elasticsuite\Index\Repository\Index\IndexRepository'
    Elasticsuite\Index\Repository\Index\IndexRepository:
        arguments:
            - '@api_platform.elasticsearch.client'

    Elasticsuite\Index\DataPersister\DocumentDataPersister:
        arguments:
            - '@Elasticsuite\Index\Repository\Document\DocumentRepositoryInterface'
        tags:
            - { name: api_platform.data_persister }

    Elasticsuite\Index\DataPersister\IndexDataPersister:
        arguments:
            - '@Elasticsuite\Index\Repository\Index\IndexRepositoryInterface'
        tags:
            - { name: api_platform.data_persister }

    Elasticsuite\Index\DataProvider\IndexDataProvider:
        arguments:
            - '@Elasticsuite\Index\Repository\Index\IndexRepositoryInterface'
        tags:
            - { name: api_platform.item_data_provider }
            - { name: api_platform.collection_data_provider }

    Elasticsuite\Index\Converter\SourceFieldToMappingField: ~
    
    Elasticsuite\Index\Service\MetadataManager:
        arguments:
            - '@Elasticsuite\Index\Converter\SourceFieldToMappingField'

    Elasticsuite\Index\Helper\IndexSettings:
        arguments:
            - '@Elasticsuite\Catalog\Repository\LocalizedCatalogRepository'
            - '%elasticsuite.indices_settings%'

    Elasticsuite\Index\Api\IndexSettingsInterface: '@Elasticsuite\Index\Service\IndexSettings'
    Elasticsuite\Index\Service\IndexSettings:
        arguments:
            - '@Elasticsuite\Index\Helper\IndexSettings'

    Elasticsuite\Index\Service\IndexOperation:
        arguments:
            - '@Elasticsuite\Index\Repository\Index\IndexRepositoryInterface'
            - '@Elasticsuite\Index\Api\IndexSettingsInterface'
            - '@Elasticsuite\Index\Service\MetadataManager'

    Elasticsuite\Index\MutationResolver\CreateIndexMutation:
        arguments:
            - '@Elasticsuite\Catalog\Repository\LocalizedCatalogRepository'
            - '@Elasticsuite\Metadata\Repository\MetadataRepository'
            - '@Elasticsuite\Index\Service\IndexOperation'
        tags:
            - { name: api_platform.graphql.mutation_resolver }

    Elasticsuite\Index\MutationResolver\BulkIndexMutation:
        arguments:
            - '@Elasticsuite\Index\Repository\Index\IndexRepositoryInterface'
        tags:
            - { name: api_platform.graphql.mutation_resolver }

    Elasticsuite\Index\MutationResolver\BulkDeleteIndexMutation:
        arguments:
            - '@Elasticsuite\Index\Repository\Index\IndexRepositoryInterface'
        tags:
            - { name: api_platform.graphql.mutation_resolver }

    Elasticsuite\Index\MutationResolver\InstallIndexMutation:
        arguments:
            - '@Elasticsuite\Index\Service\IndexOperation'
            - '@Elasticsuite\Index\Repository\Index\IndexRepositoryInterface'
        tags:
            - { name: api_platform.graphql.mutation_resolver }

    Elasticsuite\Index\MutationResolver\RefreshIndexMutation:
        arguments:
            - '@Elasticsuite\Index\Repository\Index\IndexRepositoryInterface'
        tags:
            - { name: api_platform.graphql.mutation_resolver }

    Elasticsuite\Index\DataTransformer\CreateIndexInputDataTransformer:
        arguments:
            - '@Elasticsuite\Catalog\Repository\LocalizedCatalogRepository'
            - '@Elasticsuite\Metadata\Repository\MetadataRepository'
            - '@Elasticsuite\Index\Service\IndexOperation'
        tags:
            - { name: api_platform.data_transformer }

    Elasticsuite\Index\DataTransformer\InstallIndexDataTransformer:
        arguments:
            - '@Elasticsuite\Index\Service\IndexOperation'
        tags:
            - { name: api_platform.data_transformer }

    Elasticsuite\Index\DataTransformer\RefreshIndexDataTransformer:
        arguments:
            - '@Elasticsuite\Index\Repository\Index\IndexRepositoryInterface'
        tags:
            - { name: api_platform.data_transformer }

    Elasticsuite\Index\Command\IndexClearCommand:
        arguments:
            - '@Elasticsuite\Index\Repository\Index\IndexRepositoryInterface'
            - null
        tags:
            - { name: console.command }

    Elasticsuite\Index\Command\MappingGenerateCommand:
        arguments:
            - '@Elasticsuite\Metadata\Repository\MetadataRepository'
            - '@Elasticsuite\Index\Service\MetadataManager'
            - 'elasticsuite:mapping:get'
        tags:
            - { name: console.command }

    Elasticsuite\Index\Command\MappingStatusCommand:
        arguments:
            - '@Elasticsuite\Metadata\Repository\MetadataRepository'
            - '@Elasticsuite\Index\Service\MetadataManager'
            - 'elasticsuite:mapping:status'
        tags:
            - { name: console.command }           
    
    Elasticsuite\Index\DataProvider\MappingStatusDataProvider:
        arguments:
            - '@Elasticsuite\Metadata\Repository\MetadataRepository'
            - '@Elasticsuite\Index\Service\MetadataManager'
        tags:
            - { name: api_platform.item_data_provider }
            - { name: api_platform.graphql.query_resolver }
