imports:
    - { resource: conversion/sourcefield_to_mapping.yaml }

services:
    Gally\Index\Decoration\Metadata\Document\Factory\AttributeDocumentMetadataFactory:
        decorates: api_platform.elasticsearch.metadata.document.metadata_factory
        arguments:
            - '@Gally\Fixture\Service\ElasticsearchFixtures'
            - '@api_platform.metadata.resource.metadata_factory'
            - '@Gally\ResourceMetadata\Service\ResourceMetadataManager'
            - '@.inner'
        decoration_priority: 100

    Gally\Index\Repository\Document\DocumentRepositoryInterface: '@Gally\Index\Repository\Document\DocumentRepository'
    Gally\Index\Repository\Document\DocumentRepository:
        arguments:
            - '@api_platform.elasticsearch.client'

    Gally\Index\Repository\Index\IndexRepositoryInterface: '@Gally\Index\Repository\Index\IndexRepository'
    Gally\Index\Repository\Index\IndexRepository:
        arguments:
            - '@api_platform.elasticsearch.client'
            - '@Gally\Index\Api\IndexSettingsInterface'

    Gally\Index\DataPersister\DocumentDataPersister:
        arguments:
            - '@Gally\Index\Repository\Document\DocumentRepositoryInterface'
        tags:
            - { name: api_platform.data_persister }

    Gally\Index\DataPersister\IndexDataPersister:
        arguments:
            - '@Gally\Index\Repository\Index\IndexRepositoryInterface'
        tags:
            - { name: api_platform.data_persister }

    Gally\Index\DataProvider\IndexDataProvider:
        arguments:
            - '@Gally\Index\Repository\Index\IndexRepositoryInterface'
        tags:
            - { name: api_platform.item_data_provider }
            - { name: api_platform.collection_data_provider }

    Gally\Index\Service\MetadataManager:
        arguments:
            - !tagged_iterator { tag: 'gally.mapping.source_field_converter' }

    Gally\Index\Helper\IndexSettings:
        arguments:
            - '@Gally\Catalog\Repository\LocalizedCatalogRepository'
            - '%gally.indices_settings%'

    Gally\Index\Api\IndexSettingsInterface: '@Gally\Index\Service\IndexSettings'
    Gally\Index\Service\IndexSettings:
        arguments:
            - '@Gally\Index\Helper\IndexSettings'
            - '@Gally\Analysis\Service\Config'

    Gally\Index\Service\IndexOperation:
        arguments:
            - '@Gally\Index\Repository\Index\IndexRepositoryInterface'
            - '@Gally\Index\Api\IndexSettingsInterface'
            - '@Gally\Index\Service\MetadataManager'

    Gally\Index\Service\SelfReindexOperation:
        arguments:
            - '@Gally\Metadata\Repository\MetadataRepository'
            - '@Gally\Catalog\Repository\LocalizedCatalogRepository'
            - '@Gally\Index\Service\IndexOperation'
            - '@Gally\Index\Repository\Index\IndexRepositoryInterface'
            - '@Gally\Search\Elasticsearch\Request\Container\Configuration\ContainerConfigurationProvider'

    Gally\Index\MutationResolver\CreateIndexMutation:
        arguments:
            - '@Gally\Catalog\Repository\LocalizedCatalogRepository'
            - '@Gally\Metadata\Repository\MetadataRepository'
            - '@Gally\Index\Service\IndexOperation'
        tags:
            - { name: api_platform.graphql.mutation_resolver }

    Gally\Index\MutationResolver\BulkIndexMutation:
        arguments:
            - '@Gally\Index\Repository\Index\IndexRepositoryInterface'
        tags:
            - { name: api_platform.graphql.mutation_resolver }

    Gally\Index\MutationResolver\BulkDeleteIndexMutation:
        arguments:
            - '@Gally\Index\Repository\Index\IndexRepositoryInterface'
        tags:
            - { name: api_platform.graphql.mutation_resolver }

    Gally\Index\MutationResolver\InstallIndexMutation:
        arguments:
            - '@Gally\Index\Service\IndexOperation'
            - '@Gally\Index\Repository\Index\IndexRepositoryInterface'
        tags:
            - { name: api_platform.graphql.mutation_resolver }

    Gally\Index\MutationResolver\RefreshIndexMutation:
        arguments:
            - '@Gally\Index\Repository\Index\IndexRepositoryInterface'
        tags:
            - { name: api_platform.graphql.mutation_resolver }

    Gally\Index\MutationResolver\SelfReindexMutation:
        arguments:
            - '@Gally\Index\Service\SelfReindexOperation'
        tags:
            - { name: api_platform.graphql.mutation_resolver }

    Gally\Index\DataTransformer\CreateIndexInputDataTransformer:
        arguments:
            - '@Gally\Catalog\Repository\LocalizedCatalogRepository'
            - '@Gally\Metadata\Repository\MetadataRepository'
            - '@Gally\Index\Service\IndexOperation'
        tags:
            - { name: api_platform.data_transformer }

    Gally\Index\DataTransformer\InstallIndexDataTransformer:
        arguments:
            - '@Gally\Index\Service\IndexOperation'
        tags:
            - { name: api_platform.data_transformer }

    Gally\Index\DataTransformer\RefreshIndexDataTransformer:
        arguments:
            - '@Gally\Index\Repository\Index\IndexRepositoryInterface'
        tags:
            - { name: api_platform.data_transformer }

    Gally\Index\DataTransformer\SelfReIndexDataTransformer:
        arguments:
            - '@Gally\Index\Service\SelfReindexOperation'
        tags:
            - { name: api_platform.data_transformer }

    Gally\Index\Command\IndexClearCommand:
        arguments:
            - '@Gally\Index\Repository\Index\IndexRepositoryInterface'
            - null
        tags:
            - { name: console.command }

    Gally\Index\Command\MappingGenerateCommand:
        arguments:
            - '@Gally\Metadata\Repository\MetadataRepository'
            - '@Gally\Index\Service\MetadataManager'
            - 'gally:mapping:get'
        tags:
            - { name: console.command }

    Gally\Index\Command\MappingStatusCommand:
        arguments:
            - '@Gally\Metadata\Repository\MetadataRepository'
            - '@Gally\Index\Service\MetadataManager'
            - 'gally:mapping:status'
        tags:
            - { name: console.command }           
    
    Gally\Index\DataProvider\MappingStatusDataProvider:
        arguments:
            - '@Gally\Metadata\Repository\MetadataRepository'
            - '@Gally\Index\Service\MetadataManager'
        tags:
            - { name: api_platform.item_data_provider }
            - { name: api_platform.graphql.query_resolver }
