Gally\Category\Model\Category\Configuration:
    properties:
        virtualRule:
            - Json: ~
        defaultSorting:
            - Gally\Category\Validator\DefaultSortingFieldConstraint: ~
