applications:
  admin:
    source:
      root: "/front"
    type: "nodejs:18"
    mounts:
      "/.npm":
        source: "storage"
        source_path: "npm"
    web:
      commands:
        start: "yarn start"
    build:
      flavor: none
    dependencies:
      nodejs:
        yarn: "^1.22.0"
    hooks:
      build: |
        yarn
        yarn install --frozen-lockfile --network-timeout 120000
        yarn build
      deploy: |
        set -eux
          
  api:
    source:
      root: "/api"
    type: "php:8.1"
    variables:
        env:
            APP_ENV: 'prod'

    dependencies:
      php:
        composer/composer: "^2"
    runtime:
      extensions:
        - apcu
        - pdo_pgsql
        - sodium
        - redis
    mounts:
      "/var/cache": "shared:files/cache"
      "/var/log": "shared:files/log"
      "/var/sessions": "shared:files/sessions"
    web:
      locations:
        "/":
          root: "public"
          passthru: "/index.php"
    build:
        flavor: composer
    hooks:
      build: |
          bin/console lexik:jwt:generate-keypair --skip-if-exists --no-interaction
          bin/console --env=prod assets:install --no-debug
          sed -i '/VectorSearch/d' config/bundles.php
          [ -z "${MEDIA_URL}" ] || echo "gally:\n  base_url:\n    media: '${MEDIA_URL}'" > config/packages/gally_configuration.yaml
      
      deploy: |
          bin/console --env=prod cache:clear
          bin/console doctrine:migrations:migrate -n --allow-no-migration    
    relationships:
      database: "postgresql:postgresql"
      opensearch: "opensearch:opensearch"
      redis: "redis:redis"
          
services:
  postgresql:
    type: postgresql:15

  redis:
    type: redis:7.0

  opensearch:
    type: opensearch:2
    configuration:
        plugins:
            - analysis-icu
            - analysis-phonetic


routes:
    https://{default}/:
        cache:
            enabled: false
        ssi:
            enabled: false
        type: upstream
        upstream: api:http
    
    https://{default}/admin:
        cache:
            cookies:
                - '*'
            default_ttl: 0
            enabled: true
            headers:
                - Accept
                - Accept-Language
        ssi:
            enabled: false
        type: upstream
        upstream: admin:http
    
    https://{default}/login:
        cache:
            cookies:
                - '*'
            default_ttl: 0
            enabled: true
            headers:
                - Accept
                - Accept-Language
        ssi:
            enabled: false
        type: upstream
        upstream: admin:http
    
    https://{default}/_next:
        cache:
            cookies:
                - '*'
            default_ttl: 0
            enabled: true
            headers:
                - Accept
                - Accept-Language
        ssi:
            enabled: false
        type: upstream
        upstream: admin:http
    
    https://{default}/locales:
        cache:
            cookies:
                - '*'
            default_ttl: 0
            enabled: true
            headers:
                - Accept
                - Accept-Language
        ssi:
            enabled: false
        type: upstream
        upstream: admin:http
    
    https://{default}/images:
        cache:
            cookies:
                - '*'
            default_ttl: 0
            enabled: true
            headers:
                - Accept
                - Accept-Language
        ssi:
            enabled: false
        type: upstream
        upstream: admin:http   

    https://{default}/favicon.ico:
        cache:
            cookies:
                - '*'
            default_ttl: 0
            enabled: true
            headers:
                - Accept
                - Accept-Language
        ssi:
            enabled: false
        type: upstream
        upstream: admin:http   

