elasticsuite:
    graphql_query_renaming:
        Elasticsuite\Product\Model\Product:
            renamings:
                searchProducts: products
    search_settings:
        aggregations:
            coverage_use_indexed_fields_property: false
