imports:
    - { resource: elasticsearch/request_type.yaml }

services:
    Elasticsuite\Product\Service\GraphQl\FilterManager:
        arguments:
            - '@Elasticsuite\Product\GraphQl\Type\Definition\FieldFilterInputType'
            - '%api_platform.graphql.nesting_separator%'
            - '@Elasticsuite\Category\Service\CurrentCategoryProvider'

    Elasticsuite\Product\DataProvider\ProductDataProvider:
        arguments:
            - '@serializer'
            - '@api_platform.pagination'
            - '@api_platform.metadata.resource.metadata_factory.cached'
            - '@Elasticsuite\ResourceMetadata\Service\ResourceMetadataManager'
            - '@Elasticsuite\Metadata\Repository\MetadataRepository'
            - '@Elasticsuite\Catalog\Repository\LocalizedCatalogRepository'
            - '@Elasticsuite\Search\Elasticsearch\Builder\Request\SimpleRequestBuilder'
            - '@Elasticsuite\Search\Elasticsearch\Request\Container\Configuration\ContainerConfigurationProvider'
            - '@Elasticsuite\Search\Elasticsearch\Adapter'
            - '@Elasticsuite\Product\GraphQl\Type\Definition\SortInputType'
            - '@Elasticsuite\Product\Service\GraphQl\FilterManager'
        tags:
            - { name: api_platform.collection_data_provider }

    Elasticsuite\Product\Serializer\ProductDenormalizer:
        arguments:
            - '@Elasticsuite\Stitching\Service\SerializerService'
            - '@Elasticsuite\Entity\Service\PriceGroupProvider'
            - '@Elasticsuite\Entity\Model\Attribute\AttributeFactory'
        tags:
            - { name: serializer.normalizer }

    # Declare DataFixtures
    Elasticsuite\Product\DataFixtures\ElasticsearchProductFixtures:
        arguments:
            - '@Elasticsuite\Fixture\Service\ElasticsearchFixtures'
            - '@Elasticsuite\Fixture\Service\EntityIndicesFixturesInterface'
        tags:
            - { name: doctrine.fixture.orm }
                
    Elasticsuite\Product\GraphQl\Type\Definition\SortOrder\CategoryDefaultSortOrderProvider:
        arguments:
            - '%api_platform.graphql.nesting_separator%'
        tags:
            - { name: elasticsuite.product_api.sort_order_provider, provider_name: 'category_default' }

    Elasticsuite\Product\GraphQl\Type\Definition\SortOrder\PriceDefaultSortOrderProvider:
        arguments:
            - '%api_platform.graphql.nesting_separator%'
        tags:
            - { name: elasticsuite.product_api.sort_order_provider, provider_name: 'price_default' }

    Elasticsuite\Product\GraphQl\Type\Definition\SortOrder\ScalarSortOrderProvider:
        arguments:
            - '%api_platform.graphql.nesting_separator%'
        tags:
            - { name: elasticsuite.product_api.sort_order_provider, provider_name: 'scalar' }

    Elasticsuite\Product\GraphQl\Type\Definition\SortOrder\StockDefaultSortOrderProvider:
        arguments:
            - '%api_platform.graphql.nesting_separator%'
        tags:
            - { name: elasticsuite.product_api.sort_order_provider, provider_name: 'stock_default' }

    Elasticsuite\Product\GraphQl\Type\Definition\SortOrder\SelectDefaultSortOrderProvider:
        arguments:
            - '%api_platform.graphql.nesting_separator%'
        tags:
            - { name: elasticsuite.product_api.sort_order_provider, provider_name: 'select' }

    Elasticsuite\Product\GraphQl\Type\Definition\SortInputType:
        arguments:
            - '@Elasticsuite\Search\GraphQl\Type\Definition\SortEnumType'
            - '@Elasticsuite\Metadata\Repository\SourceFieldRepository'
            - !tagged_iterator { tag: 'elasticsuite.product_api.sort_order_provider', index_by: 'provider_name' }
            - '@Elasticsuite\Entity\Service\PriceGroupProvider'
            - '@Elasticsuite\Search\Service\ReverseSourceFieldProvider'
            - '@Elasticsuite\Category\Service\CurrentCategoryProvider'
            - '%api_platform.graphql.nesting_separator%'
        tags:
            - { name: api_platform.graphql.type }

    Elasticsuite\Product\GraphQl\Type\Definition\FieldFilterInputType:
        arguments:
            - '@Elasticsuite\Search\Elasticsearch\Builder\Request\Query\Filter\FilterQueryBuilder'
            - !tagged_iterator { tag: 'elasticsuite.entity_api.filter' }
            - '@Elasticsuite\Entity\GraphQl\Type\Definition\Filter\BoolFilterInputType'
            - '@Elasticsuite\Metadata\Repository\SourceFieldRepository'
        tags:
            - { name: api_platform.graphql.type }
    
    Elasticsuite\Product\GraphQl\Type\Definition\ProductRequestTypeEnumType:
        arguments:
            - '@Elasticsuite\Search\Elasticsearch\Request\Container\Configuration\ContainerConfigurationProvider'
        tags:
            - { name: api_platform.graphql.type }
    
    Elasticsuite\Product\Service\CurrentCategoryProvider:
        arguments:
            - '@Elasticsuite\Category\Repository\CategoryRepository'

    Elasticsuite\Product\Service\PriceGroupProvider:
        arguments:
            - '@Elasticsuite\RequestContext\Service\RequestContextManager'
            - '%elasticsuite.default_price_group_id%'

    Elasticsuite\Product\Decoration\GraphQl\AddEntityTypeInContext:
        decorates: api_platform.graphql.resolver.stage.serialize
        decoration_priority: 1
        arguments:
            - '@.inner'

    elasticsuite.container_configuration.coverage_rate.factory:
        parent: 'Elasticsuite\Search\Elasticsearch\Request\Container\Configuration\GenericContainerConfigurationFactory'
        arguments:
            $aggregationProvider: '@Elasticsuite\Search\Elasticsearch\Request\Aggregation\Provider\CoverageAggregationProvider'
        tags:
            - { name: elasticsuite.container_configuration.factory, requestType: coverage_rate }
    
    Elasticsuite\Product\DataProvider\Facet\OptionDataProvider:
        parent: Elasticsuite\Search\DataProvider\Facet\OptionDataProvider
        arguments:
            $filterManager: '@Elasticsuite\Product\Service\GraphQl\FilterManager'
        tags:
            - { name: api_platform.collection_data_provider }

    Elasticsuite\Product\Service\ProductDefaultSortingOptionProvider:
        arguments:
            - '@Elasticsuite\Category\Service\CurrentCategoryProvider'
            - '@Elasticsuite\Category\Repository\CategoryConfigurationRepository'
            - '@Elasticsuite\Search\Service\SearchSettingsProvider'
            - '%api_platform.graphql.nesting_separator%'
