services:
    Elasticsuite\Product\DataProvider\ProductDataProvider:
        arguments:
            - '@serializer'
            - '@api_platform.pagination'
            - '@api_platform.metadata.resource.metadata_factory.cached'
            - '@Elasticsuite\ResourceMetadata\Service\ResourceMetadataManager'
            - '@Elasticsuite\Metadata\Repository\MetadataRepository'
            - '@Elasticsuite\Catalog\Repository\LocalizedCatalogRepository'
            - '@Elasticsuite\Search\Elasticsearch\Builder\Request\SimpleRequestBuilder'
            - '@Elasticsuite\Search\Elasticsearch\Adapter'
            - '@Elasticsuite\Product\GraphQl\Type\Definition\SortInputType'
        tags:
            - { name: api_platform.collection_data_provider }

    Elasticsuite\Product\Serializer\ProductDenormalizer:
        tags:
            - { name: serializer.normalizer }

    # Declare DataFixtures
    Elasticsuite\Product\DataFixtures\ElasticsearchProductFixtures:
        arguments:
            - '@Elasticsuite\Fixture\Service\ElasticsearchFixtures'
            - '@Elasticsuite\Fixture\Service\EntityIndicesFixturesInterface'
        tags:
            - { name: doctrine.fixture.orm }
                
    Elasticsuite\Product\GraphQl\Type\Definition\SortInputType:
        arguments:
            - '@api_platform.graphql.types_container'
            - '@Elasticsuite\Metadata\Repository\SourceFieldRepository'
            - '%api_platform.graphql.nesting_separator%'
        tags:
            - { name: api_platform.graphql.type }
