services:
    Elasticsuite\User\Repository\UserRepository:
        arguments:
            - '@Doctrine\Persistence\ManagerRegistry'
        tags:
            - { name: doctrine.repository_service }

    Elasticsuite\User\DataFixtures\Providers\HashPasswordProvider:
        arguments:
            - '@Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface'
        tags: 
          - { name: nelmio_alice.faker.provider }
