services:
    gally.entity.attribute.boolean.factory:
        parent: Gally\DependencyInjection\GenericFactory
        arguments:
            - 'Gally\Entity\Model\Attribute\Type\BooleanAttribute'
        tags:
            - { name: 'gally.entity.attribute.factory', attributeType: !php/const Gally\Entity\Model\Attribute\Type\BooleanAttribute::ATTRIBUTE_TYPE }

    gally.entity.attribute.category.factory:
        parent: Gally\DependencyInjection\GenericFactory
        arguments:
            - 'Gally\Entity\Model\Attribute\Type\CategoryAttribute'
        tags:
            - { name: 'gally.entity.attribute.factory', attributeType: !php/const Gally\Entity\Model\Attribute\Type\CategoryAttribute::ATTRIBUTE_TYPE }

    gally.entity.attribute.float.factory:
        parent: Gally\DependencyInjection\GenericFactory
        arguments:
            - 'Gally\Entity\Model\Attribute\Type\FloatAttribute'
        tags:
            - { name: 'gally.entity.attribute.factory', attributeType: !php/const Gally\Entity\Model\Attribute\Type\FloatAttribute::ATTRIBUTE_TYPE }

    gally.entity.attribute.int.factory:
        parent: Gally\DependencyInjection\GenericFactory
        arguments:
            - 'Gally\Entity\Model\Attribute\Type\IntAttribute'
        tags:
            - { name: 'gally.entity.attribute.factory', attributeType: !php/const Gally\Entity\Model\Attribute\Type\IntAttribute::ATTRIBUTE_TYPE }

    gally.entity.attribute.nested.factory:
        parent: Gally\DependencyInjection\GenericFactory
        arguments:
            - 'Gally\Entity\Model\Attribute\Type\NestedAttribute'
        tags:
            - { name: 'gally.entity.attribute.factory', attributeType: !php/const Gally\Entity\Model\Attribute\Type\NestedAttribute::ATTRIBUTE_TYPE }
                
    gally.entity.attribute.price.factory:
        parent: Gally\DependencyInjection\GenericFactory
        arguments:
            - 'Gally\Entity\Model\Attribute\Type\PriceAttribute'
        tags:
            - { name: 'gally.entity.attribute.factory', attributeType: !php/const Gally\Entity\Model\Attribute\Type\PriceAttribute::ATTRIBUTE_TYPE }
                
    gally.entity.attribute.select.factory:
        parent: Gally\DependencyInjection\GenericFactory
        arguments:
            - 'Gally\Entity\Model\Attribute\Type\SelectAttribute'
        tags:
            - { name: 'gally.entity.attribute.factory', attributeType: !php/const Gally\Entity\Model\Attribute\Type\SelectAttribute::ATTRIBUTE_TYPE }
                
    gally.entity.attribute.stock.factory:
        parent: Gally\DependencyInjection\GenericFactory
        arguments:
            - 'Gally\Entity\Model\Attribute\Type\StockAttribute'
        tags:
            - { name: 'gally.entity.attribute.factory',attributeType: !php/const Gally\Entity\Model\Attribute\Type\StockAttribute::ATTRIBUTE_TYPE }    
                
    gally.entity.attribute.text.factory:
        parent: Gally\DependencyInjection\GenericFactory
        arguments:
            - 'Gally\Entity\Model\Attribute\Type\TextAttribute'
        tags:
            - { name: 'gally.entity.attribute.factory', attributeType: !php/const Gally\Entity\Model\Attribute\Type\TextAttribute::ATTRIBUTE_TYPE }


    Gally\Entity\Model\Attribute\AttributeFactory:
        public: true
        arguments: [!tagged_iterator { tag: 'gally.entity.attribute.factory', index_by: 'attributeType' }]
