services:

    Elasticsuite\Search\Elasticsearch\Request\Aggregation\ConfigResolver\NumericAggregationConfigResolver:
        tags:
            - { name: 'elasticsuite.search.aggregation.resolver' }

    Elasticsuite\Search\Elasticsearch\Request\Aggregation\ConfigResolver\DateAggregationConfigResolver:
        tags:
            - { name: 'elasticsuite.search.aggregation.resolver' }

    Elasticsuite\Search\Elasticsearch\Request\Aggregation\ConfigResolver\SelectAggregationConfigResolver:
        tags:
            - { name: 'elasticsuite.search.aggregation.resolver' }

    Elasticsuite\Search\Elasticsearch\Request\Aggregation\ConfigResolver\CategoryAggregationConfigResolver:
        arguments:
            - '@Elasticsuite\Category\Service\CurrentCategoryProvider'
            - '@Elasticsuite\Category\Repository\CategoryRepository'
            - '@Elasticsuite\Search\Elasticsearch\Request\QueryFactory'
        tags:
            - { name: 'elasticsuite.search.aggregation.resolver' }

    Elasticsuite\Search\Elasticsearch\Request\Aggregation\ConfigResolver\PriceAggregationConfigResolver:
        arguments:
            - '@Elasticsuite\Entity\Service\PriceGroupProvider'
        tags:
            - { name: 'elasticsuite.search.aggregation.resolver' }

    Elasticsuite\Search\Elasticsearch\Request\Aggregation\ConfigResolver\StockAggregationConfigResolver:
        tags:
            - { name: 'elasticsuite.search.aggregation.resolver' }
