services:

    Elasticsuite\Search\Elasticsearch\Request\Aggregation\ConfigResolver\NumericAggregationConfigResolver:
        tags:
            - { name: 'elasticsuite.search.aggregation.resolver' }

    Elasticsuite\Search\Elasticsearch\Request\Aggregation\ConfigResolver\DateAggregationConfigResolver:
        tags:
            - { name: 'elasticsuite.search.aggregation.resolver' }

    Elasticsuite\Search\Elasticsearch\Request\Aggregation\ConfigResolver\SelectAggregationConfigResolver:
        tags:
            - { name: 'elasticsuite.search.aggregation.resolver' }

    Elasticsuite\Search\Elasticsearch\Request\Aggregation\ConfigResolver\CategoryAggregationConfigResolver:
        tags:
            - { name: 'elasticsuite.search.aggregation.resolver' }

    Elasticsuite\Search\Elasticsearch\Request\Aggregation\ConfigResolver\PriceAggregationConfigResolver:
        tags:
            - { name: 'elasticsuite.search.aggregation.resolver' }

    Elasticsuite\Search\Elasticsearch\Request\Aggregation\ConfigResolver\StockAggregationConfigResolver:
        tags:
            - { name: 'elasticsuite.search.aggregation.resolver' }
