Elasticsuite\Metadata\Model\Metadata:
    properties:
        entity:
            - NotBlank: ~
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: entity
            
Elasticsuite\Metadata\Model\SourceField:
    properties:
        code:
            - NotBlank: ~
        metadata:
            - NotBlank: ~
        type:
            - Choice: { callback: [Elasticsuite\Metadata\Model\SourceField\Type, getAvailableTypes] }
        weight:
            - Choice: { callback: [Elasticsuite\Metadata\Model\SourceField\Weight, getValidWeight] }
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
              fields: [ code, metadata ]
              message: 'An field with this code already exist for this entity.'
            
Elasticsuite\Metadata\Model\SourceFieldLabel:
    properties:
        label:
            - NotBlank: ~
        sourceField:
            - NotBlank: ~
        catalog:
            - NotBlank: ~
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
              fields: [ sourceField, catalog ]
              message: 'A label is already defined for this field and this catalog.'
            
Elasticsuite\Metadata\Model\SourceFieldOption:
    properties:
        sourceField:
            - NotBlank: ~
        code:
            - NotBlank: ~
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
              fields: [ sourceField, code ]
              message: 'An option with this code is already defined for this sourceField.'

Elasticsuite\Metadata\Model\SourceFieldOptionLabel:
    properties:
        label:
            - NotBlank: ~
        sourceFieldOption:
            - NotBlank: ~
        catalog:
            - NotBlank: ~
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
              fields: [ sourceFieldOption, catalog ]
              message: 'A label is already defined for this option and this catalog.'
