services:
    Gally\RequestContext\EventSubscriber\AddRequestContextHeadersInVary:
        arguments:
            - '@Gally\RequestContext\Service\RequestContextManager'
        tags:
            - { name: kernel.event_subscriber }

                
    Gally\RequestContext\Service\RequestContextManager:
        arguments:
            - '@request_stack'
            - '%gally.request_context%'
