services:
    Elasticsuite\Entity\Filter\SearchColumnsFilter:
        arguments: [ '@doctrine', ~, '@?logger' ]
        tags: [ 'api_platform.filter' ]

    Elasticsuite\Entity\Filter\BooleanFilter:
        arguments: [ '@doctrine', ~, '@?logger' ]
        tags: [ 'api_platform.filter' ]
