services:
    Gally\RuleEngine\Service\RuleType\CombinationRule:
        arguments:
            - '@Gally\Entity\GraphQl\Type\Definition\Filter\BoolFilterInputType'
            - '@Gally\RuleEngine\Service\RuleEngineManager'
        tags:
            - { name: gally.rule_engine.rule_type } 

    Gally\RuleEngine\Service\RuleType\AttributeRule:
        arguments:
            - '@Gally\Entity\GraphQl\Type\Definition\Filter\BoolFilterInputType'
            - '@Gally\Metadata\Repository\SourceFieldRepository'
            - '@Gally\Metadata\Repository\MetadataRepository'
            - !tagged_iterator { tag: 'gally.entity_api.filter' }
        tags:
            - { name: gally.rule_engine.rule_type }

    Gally\RuleEngine\Service\RuleEngineManager:
        lazy: true
        arguments:
            - '@Gally\Product\Service\GraphQl\FilterManager'
            - !tagged_iterator { tag: 'gally.rule_engine.rule_type' }

    Gally\RuleEngine\Resolver\RuleEngineOperatorsResolver:
        arguments:
            - '@Gally\RuleEngine\Service\RuleEngineManager'
        tags:
            - { name: api_platform.graphql.query_resolver }

    Gally\RuleEngine\Resolver\RuleEngineGraphQlFiltersResolver:
        arguments:
            - '@Gally\RuleEngine\Service\RuleEngineManager'
        tags:
            - { name: api_platform.graphql.query_resolver }
    
    Gally\RuleEngine\Controller\RuleEngineOperatorsController:
        arguments:
            - '@Gally\RuleEngine\Service\RuleEngineManager'
        calls:
            - [ setContainer, [ '@service_container' ]]
        tags: 
            - { name: controller.service_arguments }

    Gally\RuleEngine\Controller\RuleEngineGraphQlFiltersController:
        arguments:
            - '@Gally\RuleEngine\Service\RuleEngineManager'
        calls:
            - [ setContainer, [ '@service_container' ]]
        tags:
            - { name: controller.service_arguments }
                
    Gally\RuleEngine\OpenApi\RuleEngineDecorator:
        decorates: api_platform.openapi.factory
        arguments:
            - '@Gally\OpenApi\Helper\Documentation'
            - '@.inner'
