services:
    Gally\Hydra\Decoration\Serializer\DocumentationNormalizer:
        decorates: api_platform.hydra.normalizer.documentation
        arguments:
            - '@api_platform.metadata.resource.metadata_factory'
            - '@api_platform.metadata.property.name_collection_factory'
            - '@api_platform.metadata.property.metadata_factory'
            - '@.inner'
            - '@?api_platform.name_converter'

