services:
    # Declare Dummy service and its interface
    Elasticsuite\Example\Service\DummyInterface: '@Elasticsuite\Example\Service\Dummy'
    Elasticsuite\Example\Service\Dummy: ~

    # Declare command elasticsuite:example:mapping-get
    Elasticsuite\Example\Command\MappingCommand:
        arguments:
            - '@Elasticsuite\Example\Service\DummyInterface'
            - '@Symfony\Contracts\Translation\TranslatorInterface'
            - null
        tags:
            - { name: console.command }
    
    # Declare command elasticsuite:example:cache-get
    Elasticsuite\Example\Command\Cache\GetCommand:
        arguments:
            - '@Symfony\Contracts\Translation\TranslatorInterface'
            - '@Psr\Cache\CacheItemPoolInterface'
            - null
        tags:
            - { name: console.command }
        
    # Declare elasticsuite.example* cache pools
    elasticsuite.example:
        parent: cache.app.taggable
        # Will not be directly usable nor listed through cache:pool:list
        abstract: true
        tags:
            # Allowed: "clearer", "provider", "name", "namespace", "default_lifetime", "early_expiration_message_bus" and "reset"
            - { name: cache.pool }
            
    elasticsuite.example.custom.cache:
        parent: elasticsuite.example
        tags:
            # If neither 'namespace' is defined here nor a 'class' defined above, the namespace will be the environment seed prefix
            - { name: cache.pool, namespace: 'custom' }
            
    elasticsuite.example.other.cache:
        parent: elasticsuite.example
        tags:
            - { name: cache.pool, namespace: 'other' }
    
    # Declare command elasticsuite:example:cache-get-custom
    Elasticsuite\Example\Command\Cache\GetCustomCommand:
        arguments:
            - '@elasticsuite.example.custom.cache'
            - '@Symfony\Contracts\Translation\TranslatorInterface'
            - null
        tags:
            - { name: console.command }
    
    # Declare command elasticsuite:example:cache-get-other
    Elasticsuite\Example\Command\Cache\GetOtherCommand:
        arguments:
            - '@elasticsuite.example.other.cache'
            - '@Symfony\Contracts\Translation\TranslatorInterface'
            - null
        tags:
            - { name: console.command }

    # Declare command elasticsuite:example:cache-delete
    Elasticsuite\Example\Command\Cache\DeleteCommand:
        arguments:
            - '@Psr\Cache\CacheItemPoolInterface'
            - null
        tags:
            - { name: console.command }

    # Declare command elasticsuite:example:cache-invalidate-tags
    Elasticsuite\Example\Command\Cache\InvalidateTagsCommand:
        arguments:
            - ['elasticsuite.example.custom.cache', 'elasticsuite.example.other.cache']
            - null
        tags:
            - { name: console.command }

    # Declare command elasticsuite:example:cache-invalidate-tags-injected
    Elasticsuite\Example\Command\Cache\InvalidateTagsInjectedCommand:
        arguments:
            - ['@elasticsuite.example.custom.cache', '@elasticsuite.example.other.cache']
            - null
        tags:
            - { name: console.command }

    # Declare DataFixtures
    Elasticsuite\Example\DataFixtures\ExampleFixtures:
        arguments:
            - '@Elasticsuite\Fixture\Service\ElasticsearchFixtures'
        tags:
            - { name: doctrine.fixture.orm }

    # Declare repository
    Elasticsuite\Example\Repository\Document\DocumentRepositoryInterface: '@Elasticsuite\Example\Repository\Document\DocumentRepository'
    Elasticsuite\Example\Repository\Document\DocumentRepository:
        arguments:
            - '@api_platform.elasticsearch.client'

    Elasticsuite\Example\Repository\Index\IndexRepositoryInterface: '@Elasticsuite\Example\Repository\Index\IndexRepository'
    Elasticsuite\Example\Repository\Index\IndexRepository:
        arguments:
            - '@api_platform.elasticsearch.client'

    Elasticsuite\Example\Repository\Category\CategoryRepository:
        arguments:
            - '@Doctrine\Persistence\ManagerRegistry'
        tags:
            - { name: doctrine.repository_service } 

    # Declare denormalizer
    Elasticsuite\Example\Serializer\AttributesDenormalizer:
        tags:
            - { name: serializer.normalizer }

    # Declare data persister
    Elasticsuite\Example\DataPersister\DocumentDataPersister:
        arguments:
            - '@Elasticsuite\Example\Repository\Document\DocumentRepositoryInterface'
        tags:
            - { name: api_platform.data_persister }

    Elasticsuite\Example\DataPersister\IndexDataPersister:
        arguments:
            - '@Elasticsuite\Example\Repository\Index\IndexRepositoryInterface'
        tags:
            - { name: api_platform.data_persister }

    # Declare data provider
    Elasticsuite\Example\DataProvider\IndexDataProvider:
        arguments:
            - '@Elasticsuite\Example\Repository\Index\IndexRepositoryInterface'
        tags:
            - { name: api_platform.item_data_provider }
            - { name: api_platform.collection_data_provider }
