services:  
    # Declare command elasticsuite:example:cache-get
    Elasticsuite\Example\Command\Cache\GetCommand:
        arguments:
            - '@Symfony\Contracts\Translation\TranslatorInterface'
            - '@Psr\Cache\CacheItemPoolInterface'
            - null
        tags:
            - { name: console.command }
        
    # Declare elasticsuite.example* cache pools
    elasticsuite.example:
        parent: cache.app.taggable
        # Will not be directly usable nor listed through cache:pool:list
        abstract: true
        tags:
            # Allowed: "clearer", "provider", "name", "namespace", "default_lifetime", "early_expiration_message_bus" and "reset"
            - { name: cache.pool }
            
    elasticsuite.example.custom.cache:
        parent: elasticsuite.example
        tags:
            # If neither 'namespace' is defined here nor a 'class' defined above, the namespace will be the environment seed prefix
            - { name: cache.pool, namespace: 'custom' }
            
    elasticsuite.example.other.cache:
        parent: elasticsuite.example
        tags:
            - { name: cache.pool, namespace: 'other' }
    
    # Declare command elasticsuite:example:cache-get-custom
    Elasticsuite\Example\Command\Cache\GetCustomCommand:
        arguments:
            - '@elasticsuite.example.custom.cache'
            - '@Symfony\Contracts\Translation\TranslatorInterface'
            - null
        tags:
            - { name: console.command }
    
    # Declare command elasticsuite:example:cache-get-other
    Elasticsuite\Example\Command\Cache\GetOtherCommand:
        arguments:
            - '@elasticsuite.example.other.cache'
            - '@Symfony\Contracts\Translation\TranslatorInterface'
            - null
        tags:
            - { name: console.command }

    # Declare command elasticsuite:example:cache-delete
    Elasticsuite\Example\Command\Cache\DeleteCommand:
        arguments:
            - '@Psr\Cache\CacheItemPoolInterface'
            - null
        tags:
            - { name: console.command }

    # Declare command elasticsuite:example:cache-invalidate-tags
    Elasticsuite\Example\Command\Cache\InvalidateTagsCommand:
        arguments:
            - ['elasticsuite.example.custom.cache', 'elasticsuite.example.other.cache']
            - null
        tags:
            - { name: console.command }

    # Declare command elasticsuite:example:cache-invalidate-tags-injected
    Elasticsuite\Example\Command\Cache\InvalidateTagsInjectedCommand:
        arguments:
            - ['@elasticsuite.example.custom.cache', '@elasticsuite.example.other.cache']
            - null
        tags:
            - { name: console.command }
