api_platform:
    title: Elasticsuite API
    version: 1.0.0
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    exception_to_status:
        # The 4 following handlers are registered by default, keep those lines to prevent unexpected side effects
        Symfony\Component\Serializer\Exception\ExceptionInterface: 400 # Use a raw status code (recommended)
        # ApiPlatform\Core\Exception\InvalidArgumentException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_BAD_REQUEST
        ApiPlatform\Core\Exception\InvalidArgumentException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_BAD_REQUEST
        ApiPlatform\Core\Exception\FilterValidationException: 400
        Doctrine\ORM\OptimisticLockException: 409
        # Validation exception
        ApiPlatform\Core\Bridge\Symfony\Validator\Exception\ValidationException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_UNPROCESSABLE_ENTITY
        ApiPlatform\Core\Validator\Exception\ValidationException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_UNPROCESSABLE_ENTITY
    # Mercure integration, remove if unwanted
    # mercure: ~
    # Good cache defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
            max_age: 0
            shared_max_age: 3600
    collection:
        pagination:
            client_enabled: true # Enabled by default because this value cannot be specified by GraphQL endpoint
            client_items_per_page: true # Enabled by default because this value cannot be specified by GraphQL endpoint
            page_parameter_name: currentPage
            items_per_page_parameter_name: pageSize
            items_per_page: 20
