postgresql:
    type: postgresql:15
    disk: 256
       
opensearch:        
    type: opensearch:2
    disk: 256
    configuration:
        plugins:
            - analysis-icu
            - analysis-phonetic
            - opensearch-ml-plugin
            - neural-search
            - opensearch-knn

redis:
    type: redis-persistent:7.0
    disk: 256
