elasticsuite:
    relevance:
        global:
            request_types:
                generic:
                    fulltext:
                        minimumShouldMatch: '100%'
                        tieBreaker: 1.0
                    phraseMatch:
                        enabled: false
                        boost: 0
                    cutOffFrequency:
                        value: 0.15
                    fuzziness:
                        enabled: true
                        value: !php/const Elasticsuite\Search\Elasticsearch\Request\Container\RelevanceConfiguration\FuzzinessConfig::VALUE_AUTO
                        prefixLength: 1
                        maxExpansions: 10
                    phonetic:  
                        enabled: true
