elasticsuite:
    graphql_query_renaming:
        Elasticsuite\Search\Model\Document:
            renamings:
                searchDocuments: documents
    search_settings:
        aggregations:
            coverage_use_indexed_fields_property: false
