services:
    Elasticsuite\Search\Repository\Facet\ConfigurationRepository:
        arguments:
            - '@Doctrine\Persistence\ManagerRegistry'
        tags:
            - { name: doctrine.repository_service }
