Elasticsuite\Catalog\Model\Catalog:
    properties:
        code:
            - NotBlank: ~

Elasticsuite\Catalog\Model\LocalizedCatalog:
    properties:
        code:
            - NotBlank: ~
        catalog:
            - NotBlank: ~
        locale:
            - Regex: '/[a-z]{2}_[A-Z]{2}$/'
            - Length:
                  min: 5
                  max: 5
