#controllers:
#    resource: ../src/Controller/
#    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

gally_security:
    resource: '@GallyBundle/src/Security/Resources/config/routing.yml'
