#controllers:
#    resource: ../src/Controller/
#    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

# TODO : Move this into Elasticsuite bundle ?
elasticsuite_security:
    resource: '@ElasticsuiteBundle/src/Security/Resources/config/routing.yml'
