#controllers:
#    resource: ../src/Controller/
#    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

elasticsuite_security:
    resource: '@ElasticsuiteBundle/src/Security/Resources/config/routing.yml'
