services:
    Elasticsuite\Category\Repository\CategoryRepository:
        arguments:
            - '@Doctrine\Persistence\ManagerRegistry'
        tags:
            - { name: doctrine.repository_service }

    Elasticsuite\Category\Repository\CategoryConfigurationRepository:
        arguments:
            - '@Doctrine\Persistence\ManagerRegistry'
        tags:
            - { name: doctrine.repository_service }

    # Declare DataFixtures
    Elasticsuite\Category\DataFixtures\ElasticsearchCategoryFixtures:
        arguments:
            - '@Elasticsuite\Fixture\Service\ElasticsearchFixtures'
        tags:
            - { name: doctrine.fixture.orm }

    Elasticsuite\Category\Service\CategorySynchronizer:
        arguments:
            - '@Elasticsuite\Category\Repository\CategoryRepository'
            - '@Elasticsuite\Category\Repository\CategoryConfigurationRepository'
            - '@Elasticsuite\Search\Elasticsearch\RequestFactoryInterface'
            - '@Elasticsuite\Search\Elasticsearch\Builder\Request\Query\QueryBuilder'
            - '@Elasticsuite\Search\Elasticsearch\Adapter'
            - '@doctrine.orm.entity_manager'
            
    Elasticsuite\Category\Decoration\SyncCategoryDataAfterBulk:
        decorates: Elasticsuite\Index\MutationResolver\BulkIndexMutation
        arguments:
            - '@.inner'
            - '@Elasticsuite\Category\Service\CategorySynchronizer'
            - '@Elasticsuite\Index\Service\IndexSettings'
            - '@Elasticsuite\Index\Repository\Index\IndexRepository'
        decoration_priority: 100
            
    Elasticsuite\Category\Decoration\SyncCategoryDataAfterBulkDelete:
        decorates: Elasticsuite\Index\MutationResolver\BulkDeleteIndexMutation
        arguments:
            - '@.inner'
            - '@Elasticsuite\Category\Service\CategorySynchronizer'
            - '@Elasticsuite\Index\Service\IndexSettings'
            - '@Elasticsuite\Index\Repository\Index\IndexRepository'
        decoration_priority: 100
            
    Elasticsuite\Category\Decoration\SyncCategoryDataAfterInstall:
        decorates: Elasticsuite\Index\MutationResolver\InstallIndexMutation
        arguments:
            - '@.inner'
            - '@Elasticsuite\Category\Service\CategorySynchronizer'
        decoration_priority: 100
        
    Elasticsuite\Category\DataProvider\CategorySortingOptionDataProvider:
        arguments:
            - '@Elasticsuite\Metadata\Repository\SourceFieldRepository'
        tags:
            - { name: api_platform.collection_data_provider }
        
    Elasticsuite\Category\Validator\DefaultSortingFieldConstraintValidator:
        arguments:
            - '@Elasticsuite\Category\DataProvider\CategorySortingOptionDataProvider'
        tags:
            - { name: validator.constraint_validator } 
    
    Elasticsuite\Category\Controller\CategoryConfigurationGet:
        arguments:
            - '@Elasticsuite\Category\Repository\CategoryConfigurationRepository'
            - '@request_stack'
        calls:
            - [ setContainer, [ '@service_container' ] ]
        tags:
            - { name: controller.service_arguments }
    
    Elasticsuite\Category\Resolver\ConfigurationResolver:
        arguments:
            - '@Elasticsuite\Category\Repository\CategoryConfigurationRepository'
        tags:
            - { name: api_platform.graphql.query_resolver }
    
    Elasticsuite\Category\Service\CategoryTreeBuilder:
        arguments:
            - '@Elasticsuite\Catalog\Repository\CatalogRepository'
            - '@Elasticsuite\Catalog\Repository\LocalizedCatalogRepository'
            - '@Elasticsuite\Category\Repository\CategoryRepository'
            - '@Elasticsuite\Category\Repository\CategoryConfigurationRepository'
            - '@Elasticsuite\Catalog\Service\DefaultCatalogProvider'
    
    Elasticsuite\Category\Resolver\CategoryTreeResolver:
        arguments:
            - '@Elasticsuite\Category\Service\CategoryTreeBuilder'
        tags:
            - { name: api_platform.graphql.query_resolver }
    
    Elasticsuite\Category\Controller\GetCategoryTree:
        arguments:
            - '@Elasticsuite\Category\Service\CategoryTreeBuilder'
            - '@request_stack'
        calls:
            - [ setContainer, [ '@service_container' ] ]
        tags:
            - { name: controller.service_arguments }
