Elasticsuite\Category\Model\Category\Configuration:
    properties:
        defaultSorting:
            - Elasticsuite\Category\Validator\DefaultSortingFieldConstraint:
                  sortOptions:
                      - "position"
