# Add this compose file to your docker compose command if you want to use gally with elasticsearch 8 (NB opensearch 2 is recommended)
services:
  search:
    build:
      context: docker/search
      target: gally_elasticsearch8
    # restart: unless-stopped
    environment:
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # 512 Mo HEAP
      - cluster.routing.allocation.disk.threshold_enabled=false # Avoid ES going read-only because low disk space availability
      - xpack.security.enabled=false # disable ssl security
      - action.destructive_requires_name='false' #Allow to delete indices with wildcard
    volumes:
      - es_data8:/usr/share/elasticsearch/data:rw,z

volumes:
  es_data8:
