# Add this compose file to your docker compose command if you want to use gally to develop connector locally
services:
  proxy:
    networks:
      default:
        aliases:
          - ${SERVER_NAME:-gally.localhost}

networks:  
  default:
    name: 'connectors-proxy'
