# Add this compose file to your docker compose command if you want to enable gpu acceleration for vector computation (WIP)
services:  
  search-ml:
    build:
      context: docker/search
      target: gally_opensearch2_gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
