coop_tilleuls_forgot_password:
    resource: "@CoopTilleulsForgotPasswordBundle/Resources/config/routing.xml"
    prefix: '%route_prefix%/forgot_password'
    
coop_tilleuls_forgot_password.get_token:
    path: '%route_prefix%/forgot_password/{tokenValue}'
    methods: [ GET ]
    defaults:
        _controller: Gally\User\Controller\GetTokenController
