services:
    gally.search.request.query.boolean.factory:
        parent: Gally\DependencyInjection\GenericFactory
        arguments:
            - 'Gally\Search\Elasticsearch\Request\Query\Boolean'
        tags:
            - { name: 'gally.search.request.query.factory', queryType: 'boolQuery' }

    gally.search.request.query.common.factory:
        parent: Gally\DependencyInjection\GenericFactory
        arguments:
            - 'Gally\Search\Elasticsearch\Request\Query\Common'
        tags:
            - { name: 'gally.search.request.query.factory', queryType: 'commonQuery' }

    gally.search.request.query.exists.factory:
        parent: Gally\DependencyInjection\GenericFactory
        arguments:
            - 'Gally\Search\Elasticsearch\Request\Query\Exists'
        tags:
            - { name: 'gally.search.request.query.factory', queryType: 'existsQuery' }

    gally.search.request.query.filtered.factory:
        parent: Gally\DependencyInjection\GenericFactory
        arguments:
            - 'Gally\Search\Elasticsearch\Request\Query\Filtered'
        tags:
            - { name: 'gally.search.request.query.factory', queryType: 'filteredQuery' }

    gally.search.request.query.functionscore.factory:
        parent: Gally\DependencyInjection\GenericFactory
        arguments:
            - 'Gally\Search\Elasticsearch\Request\Query\FunctionScore'
        tags:
            - { name: 'gally.search.request.query.factory', queryType: 'functionScore' }

    gally.search.request.query.matchphraseprefix.factory:
        parent: Gally\DependencyInjection\GenericFactory
        arguments:
            - 'Gally\Search\Elasticsearch\Request\Query\MatchPhrasePrefix'
        tags:
            - { name: 'gally.search.request.query.factory', queryType: 'matchPhrasePrefixQuery' }

    gally.search.request.query.match.factory:
        parent: Gally\DependencyInjection\GenericFactory
        arguments:
            - 'Gally\Search\Elasticsearch\Request\Query\MatchQuery'
        tags:
            - { name: 'gally.search.request.query.factory', queryType: 'matchQuery' }

    gally.search.request.query.missing.factory:
        parent: Gally\DependencyInjection\GenericFactory
        arguments:
            - 'Gally\Search\Elasticsearch\Request\Query\Missing'
        tags:
            - { name: 'gally.search.request.query.factory', queryType: 'missingQuery' }

    gally.search.request.query.morelikethis.factory:
        parent: Gally\DependencyInjection\GenericFactory
        arguments:
            - 'Gally\Search\Elasticsearch\Request\Query\MoreLikeThis'
        tags:
            - { name: 'gally.search.request.query.factory', queryType: 'moreLikeThisQuery' }

    gally.search.request.query.multimatch.factory:
        parent: Gally\DependencyInjection\GenericFactory
        arguments:
            - 'Gally\Search\Elasticsearch\Request\Query\MultiMatch'
        tags:
            - { name: 'gally.search.request.query.factory', queryType: 'multiMatchQuery' }

    gally.search.request.query.nested.factory:
        parent: Gally\DependencyInjection\GenericFactory
        arguments:
            - 'Gally\Search\Elasticsearch\Request\Query\Nested'
        tags:
            - { name: 'gally.search.request.query.factory', queryType: 'nestedQuery' }

    gally.search.request.query.not.factory:
        parent: Gally\DependencyInjection\GenericFactory
        arguments:
            - 'Gally\Search\Elasticsearch\Request\Query\Not'
        tags:
            - { name: 'gally.search.request.query.factory', queryType: 'notQuery' }

    gally.search.request.query.range.factory:
        parent: Gally\DependencyInjection\GenericFactory
        arguments:
            - 'Gally\Search\Elasticsearch\Request\Query\Range'
        tags:
            - { name: 'gally.search.request.query.factory', queryType: 'rangeQuery' }

    gally.search.request.query.term.factory:
        parent: Gally\DependencyInjection\GenericFactory
        arguments:
            - 'Gally\Search\Elasticsearch\Request\Query\Term'
        tags:
            - { name: 'gally.search.request.query.factory', queryType: 'termQuery' }

    gally.search.request.query.terms.factory:
        parent: Gally\DependencyInjection\GenericFactory
        arguments:
            - 'Gally\Search\Elasticsearch\Request\Query\Terms'
        tags:
            - { name: 'gally.search.request.query.factory', queryType: 'termsQuery' }

    Gally\Search\Elasticsearch\Request\QueryFactory:
        public: true
        arguments: [!tagged_iterator { tag: 'gally.search.request.query.factory', index_by: 'queryType' }]
