name: QA

on:
  push:
    branches:
      - master
  pull_request: ~

jobs:
  qa:
    name: Code-Quality-Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - uses: php-actions/composer@v6
        with: 
          php_version: "8.1"
      - name: PHP-CS-Fixer
        run: ./vendor/bin/php-cs-fixer fix --path-mode=intersection --diff --dry-run src
      - name: PHPStan
        run: ./vendor/bin/phpstan analyse src
