services:
    Elasticsuite\RuleEngine\Service\RuleType\CombinationRule:
        arguments:
            - '@Elasticsuite\Entity\GraphQl\Type\Definition\Filter\BoolFilterInputType'
            - '@Elasticsuite\RuleEngine\Service\RuleEngineManager'
        tags:
            - { name: elasticsuite.rule_engine.rule_type } 

    Elasticsuite\RuleEngine\Service\RuleType\AttributeRule:
        arguments:
            - '@Elasticsuite\Entity\GraphQl\Type\Definition\Filter\BoolFilterInputType'
            - '@Elasticsuite\Metadata\Repository\SourceFieldRepository'
            - '@Elasticsuite\Metadata\Repository\MetadataRepository'
            - !tagged_iterator { tag: 'elasticsuite.entity_api.filter' }
        tags:
            - { name: elasticsuite.rule_engine.rule_type }

    Elasticsuite\RuleEngine\Service\RuleEngineManager:
        lazy: true
        arguments:
            - '@Elasticsuite\Product\Service\GraphQl\FilterManager'
            - !tagged_iterator { tag: 'elasticsuite.rule_engine.rule_type' }

    Elasticsuite\RuleEngine\Resolver\RuleEngineOperatorsResolver:
        arguments:
            - '@Elasticsuite\RuleEngine\Service\RuleEngineManager'
        tags:
            - { name: api_platform.graphql.query_resolver }

    Elasticsuite\RuleEngine\Resolver\RuleEngineGraphQlFiltersResolver:
        arguments:
            - '@Elasticsuite\RuleEngine\Service\RuleEngineManager'
        tags:
            - { name: api_platform.graphql.query_resolver }
    
    Elasticsuite\RuleEngine\Controller\RuleEngineOperatorsController:
        arguments:
            - '@Elasticsuite\RuleEngine\Service\RuleEngineManager'
        calls:
            - [ setContainer, [ '@service_container' ]]
        tags: 
            - { name: controller.service_arguments }

    Elasticsuite\RuleEngine\Controller\RuleEngineGraphQlFiltersController:
        arguments:
            - '@Elasticsuite\RuleEngine\Service\RuleEngineManager'
        calls:
            - [ setContainer, [ '@service_container' ]]
        tags:
            - { name: controller.service_arguments }
                
    Elasticsuite\RuleEngine\OpenApi\RuleEngineDecorator:
        decorates: api_platform.openapi.factory
        arguments:
            - '@Elasticsuite\OpenApi\Helper\Documentation'
            - '@.inner'
