name: Deploy master

on:
  schedule:
    - cron: '30 5 * * 1-5'
  workflow_dispatch:
    inputs:
      skip_tests:
        description: 'Skip tests before delivery ?'
        type: boolean
        default: false
        required: false

jobs:
  tests:
    name: Tests
    if: ${{ inputs.skip_tests == false }}
    uses: ./.github/workflows/tests.yml
    with:
      ref: master
    secrets: inherit
  
  deploy-master:
    needs: tests
    name: Deploy master
    if: |
      always() && 
      (needs.tests.result == 'success' || needs.tests.result == 'skipped')
    uses: ./.github/workflows/deploy-int.yml
    with:
      back_branch: master
      front_branch: main
      composer_version: dev-master
    secrets: inherit
