name: Deploy demo

on:
  workflow_dispatch:
    inputs:
      skip_tests:
        description: 'Skip tests before delivery ?'
        type: boolean
        default: false
        required: false

jobs:
  tests:
    name: Tests
    if: ${{ inputs.skip_tests == false && startsWith(github.ref, 'refs/tags/') }}
    uses: ./.github/workflows/tests.yml
    with:
      ref: ${{ github.ref_name }}
    secrets: inherit

  deploy-demo:
    needs: tests
    name: Deploy demo
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    uses: ./.github/workflows/deploy-int.yml
    with:
      back_branch: ${{ github.ref_name }}
      front_branch: ${{ format('v{0}', github.ref_name) }}
      composer_version: ${{ github.ref_name }}
    secrets:
      AWS_DEPLOY_KEY: ${{ secrets.AWS_DEPLOY_KEY }}
      AWS_HOSTNAME: ${{ secrets.AWS_HOSTNAME_DEMO }}
      AWS_USER: ${{ secrets.AWS_USER }}
      APP_SECRET: ${{ secrets.APP_SECRET }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
