name: Deploy 1.1.x

on:
  schedule:
    - cron: '30 4 * * 1-5'
  workflow_dispatch:
    inputs:
      skip_tests:
        description: 'Skip tests before delivery ?'
        type: boolean
        default: false
        required: false

jobs:
  tests:
    name: Tests
    if: ${{ inputs.skip_tests == false }}
    uses: ./.github/workflows/tests.yml
    with:
      version: 1.1.x
      last_published_version: 1.1.0
    secrets:
      COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
      PACKAGIST_URL: ${{ secrets.PACKAGIST_URL }}
  
  deploy-1_1_X:
    needs: tests
    name: Deploy 1.1.x
    if: |
      always() && 
      (needs.tests.result == 'success' || needs.tests.result == 'skipped')
    uses: ./.github/workflows/deploy-int.yml
    with:
      version: 1.1.x
      last_published_version: 1.1.0
    secrets:
      AWS_DEPLOY_KEY: ${{ secrets.AWS_DEPLOY_KEY }}
      AWS_HOSTNAME: ${{ secrets.AWS_HOSTNAME_STABLE }}
      AWS_USER: ${{ secrets.AWS_USER }}
      APP_SECRET: ${{ secrets.APP_SECRET }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
      PACKAGIST_URL: ${{ secrets.PACKAGIST_URL }}
