services:    
    Gally\Catalog\Repository\CatalogRepository:
        arguments:
            - '@Doctrine\Persistence\ManagerRegistry'
        tags:
            - { name: doctrine.repository_service } 

    Gally\Catalog\Repository\LocalizedCatalogRepository:
        arguments:
            - '@Doctrine\Persistence\ManagerRegistry'
        tags:
            - { name: doctrine.repository_service }
            
    Gally\Catalog\DataPersister\LocalizedCatalogDataPersister:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@Gally\Catalog\Repository\LocalizedCatalogRepository'
        tags:
            - { name: api_platform.data_persister }
                
    Gally\Catalog\Service\DefaultCatalogProvider:
        arguments:
            - '@Gally\Catalog\Repository\LocalizedCatalogRepository'
            
