services:
    Elasticsuite\Stitching\Decoration\GraphQl\Type\StitchingFieldsBuilder:
        decorates: api_platform.graphql.fields_builder
        arguments:
            - '@Elasticsuite\Metadata\Repository\MetadataRepository'
            - '@ApiPlatform\Core\Metadata\Resource\Factory\ResourceMetadataFactoryInterface'
            - '@Elasticsuite\ResourceMetadata\Service\ResourceMetadataManager'
            - '@api_platform.graphql.types_container'
            - '@.inner'

    Elasticsuite\Stitching\Serializer\GraphQl\StitchingNormalizer:
        arguments:
            - '@Elasticsuite\Metadata\Repository\MetadataRepository'
            - '@ApiPlatform\Core\Metadata\Resource\Factory\ResourceMetadataFactoryInterface'
            - '@Elasticsuite\ResourceMetadata\Service\ResourceMetadataManager'
            - '@Elasticsuite\Stitching\Service\SerializerService'
        tags:
            - { name: 'serializer.normalizer' }

    Elasticsuite\Stitching\Service\SerializerService:
        arguments:
            - '@Elasticsuite\Metadata\Repository\MetadataRepository'
            - '@Elasticsuite\Metadata\Repository\SourceFieldRepository'
