Gally\Catalog\Model\Catalog:
    properties:
        code:
            - NotBlank: ~

Gally\Catalog\Model\LocalizedCatalog:
    properties:
        code:
            - NotBlank: ~
        catalog:
            - NotBlank: ~
        locale:
            - NotBlank: ~
            - Regex: '/[a-z]{2}_[A-Z]{2}$/'
            - Length:
                  min: 5
                  max: 5
            - Locale: ~
        currency:
            - NotBlank: ~
            - Currency: ~
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
              fields: [code, locale]
              errorPath: locale
              message: 'This code and locale couple already exists.'                  
